### ISSUE TITLE
Group of radio buttons

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#10]
A list of radio buttons. The "name" attribute MUST share the same value.
The "checked" attribute can be used to choose which one is pre-selected.

It's on Contact - maybe more places. 

```
BLOCK f-radio-group
```

**Comment by troldmand** [comment]
This on is incorporated in f-button, on #8

**Comment by dotnetCarpenter** [comment]
@troldmand This is the radio group used in the payment module and not #8. Not sure if we should re-open this or it will be part of the payment module and **not** be used anywhere else?
