### ISSUE TITLE
f-media

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#15]
An image or video with an optional caption text. It has the same width as its container block e.i. put it in a grid (`f-row` or `f-column`).

```
BLOCK f-media
    ELEMENT f-media__media
    ELEMENT f-media__caption
```

**Comment by dotnetCarpenter** [comment]
I renamed this to `f-media` because we can use the same styling for both video and image. The branch is still named 15-image though.

**Comment by troldmand** [comment]
@dotnetCarpenter Still working on this branch?

**Comment by dotnetCarpenter** [comment]
@troldmand nope. I'll delete it

**Comment by dotnetCarpenter** [comment]
Need to center media on mobile

**Comment by dotnetCarpenter** [comment]
Add description for video aspect ratio

**Comment by dotnetCarpenter** [comment]
Removing all the left/right modifier stuff as we don't have it in any design and are using `f-row` anyway to layout images and text.
