### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#17]
Has a full width background image with text content on top. Image inserted as html img tag and via js set as css background-image. The image is initial hidden but is reveal in a translateY/opacity movement, when the js has run.

```
    BLOCK f-hero
        ELEMENT f-hero__heading
        ELEMENT f-hero__text
```

**Comment by dotnetCarpenter** [comment]
Need grid #47 to work before this is done

**Comment by dotnetCarpenter** [comment]
test follow up push
