### ISSUE TITLE
Numbered info card

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#19]
A numbered block with heading and separator. Below the separator, is text and image. 
As seen on "How does it work".

```
BLOCK f-numbered-block
    ELEMENT f-numbered-block__number
    ELEMENT f-numbered-block__heading
    ~~ELEMENT f-numbered block__separator~~
    ELEMENT f-numbered-block__text
    ELEMENT f-numbered-block__image
```

**Comment by troldmand** [comment]
I need to go on, when the grid is merged. :-) 
Then also input the correct pictures. 

Finally, the scrollme.js needs our .js setup to work first.

**Comment by dotnetCarpenter** [comment]
#47 is merged in to master, so you can go ahead with the styling.
#50 is pretty far from being ready, so that blocks this. I think you should move this to backlog in waffle when you have styled this with the grid.

**Comment by troldmand** [comment]
We're waiting for the WebComponents! We just need to include scrollme images now :-)

**Comment by dotnetCarpenter** [comment]
Damn.. it still looks wrong. The list should left align with the rest of the content.

![f-list](https://cloud.githubusercontent.com/assets/43763/14998113/9d129878-1182-11e6-9075-2525504a5d1d.png)

**Comment by troldmand** [comment]
That's a point for f-list, not for f-info-card :-)
