### ISSUE TITLE
f-one-liner-border

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#20]
One line of text. A kind to 11 but with different font size and a border. As seen on ORGANIZE-button. 

```
BLOCK f-one-liner-border
```

**Comment by troldmand** [comment]
@dotnetCarpenter maybe not the most intuitive name? It's for the organize button - and hopefully also other places...

**Comment by troldmand** [comment]
Wooops! It's a button!

**Comment by troldmand** [comment]
Needs to be made with a modifer on buttons ...

**Comment by dotnetCarpenter** [comment]
moved to #40
