### ISSUE TITLE
Project thumbnails f-project-thumbnail

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#22]
Links to project page. Image fades into color on mouse hover on desktop. On mobile, the images are in color.

```
BLOCK f-project-thumbnail
    MODIFIER f-project-thumbnail_reverse
    ELEMENT f-project-thumbnail__content
    ELEMENT f-project-thumbnail__heading
    ELEMENT f-project-thumbnail__byline
    ELEMENT f-project-thumbnail__text
    ELEMENT f-project-thumbnail__summary
    ELEMENT f-project-thumbnail__progress
    ELEMENT f-project-thumbnail__image
        ELEMENT f-project-thumbnail__image-text
```

Tasks:
- [ ] ~blur filter when "being organized" `f-project-thumbnail__image-text`~ see #113
- [ ] write _Being organized_ in `f-project-thumbnail__image-text`
- [x] crop image

Linked with #23

**Comment by dotnetCarpenter** [comment]
Issues has been created for known bugs in this block.
#118 
#116 
#115 
#113 
New feature:
#114 

Closing this and track this in separate issues
