### ISSUE TITLE
Mini project thumbnail

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#23]
The mini edition, showed on phones, and under the big one on desktop (grouped by three) on frontpage.

```
BLOCK f-miniproject-thumbnail
    ELEMENT f-miniproject-thumbnail__image
    ELEMENT f-miniproject-thumbnail__image-text
    ELEMENT f-miniproject-thumbnail__heading (1-2 lines but same height, flexbox centered)
    ELEMENT f-miniproject-thumbnail__byline
    ELEMENT f-miniproject-thumbnail__text
    ELEMENT f-miniproject-thumbnail__progress
```

**Comment by troldmand** [comment]
Yo @dotnetCarpenter, I think we need to sit down about this one. There's some more to-do's on it (pictures for mobile version & scaling in general), so let's talk!

**Comment by dotnetCarpenter** [comment]
BLOCKED by #50 Settle on an architecture for including js to blocks
Need BEM refactoring - `f-progress`

**Comment by troldmand** [comment]
Here's the design. Don't throw too much time into adjusting the filter on the 'being organized' - we'll get back to that. 

![skaermbillede 2016-05-10 kl 16 02 05](https://cloud.githubusercontent.com/assets/9819978/15149241/0721e156-16c9-11e6-8c7b-408b8f2bf92b.png)
