### ISSUE TITLE
Funding progress indicator f-progress

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#25]
```
BLOCK f-progress
MODIFIER f-progress_horizontal
    ELEMENT f-progress__bar
        ELEMENT f-progress__value
    ELEMENT f-progress__data
    ELEMENT f-progress__data-element
```

**Comment by dotnetCarpenter** [comment]
@troldmand Will you take look, before I merge this in? Look at PR #80

**Comment by troldmand** [comment]
Looks great! I'm going to adjust the bottom margin tho, it needs some spacing between the ... progress and ... data. 

@dotnetCarpenter let me know if it should've been done in a different way :-)

**Comment by dotnetCarpenter** [comment]
Need `f-progress_small` modifier. BLOCKED by Mini project thumbnail #23

**Comment by dotnetCarpenter** [comment]
Instead of having a `f-progress_small` modifier, we use this as a **mix** and style it within `f-thumbnail.css`.

> Ref: Issue #22 and PR #117
