### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#26]
```
BLOCK f-footer
```

**Comment by magiker420** [comment]
A block of blocks, so waiting with this one until making webcomponents.

**Comment by dotnetCarpenter** [comment]
@magiker420  If you have made a branch and pushed it to github, can you make a reference to it here? Just use "# + number" in a comment

**Comment by dotnetCarpenter** [comment]
move to backlog until we have web components

**Comment by dotnetCarpenter** [comment]
In trello: https://trello.com/c/4VScEfKz/32-review-icons-1
