### ISSUE TITLE
News letter signup form f-signup

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#29]
```
BLOCK f-signup
    MODIFIER f-signup_error
    ELEMENT f-signup__label
    ELEMENT f-signup__feedback-text
    ELEMENT f-signup__input
    ELEMENT f-signup__button
```

**Comment by troldmand** [comment]
@dotnetCarpenter 

YO-YON, jeg kan ikke hit ud af koden efter du lavede den korrekt - så jeg håber over på noget andet og så kan du enten få lov, eller også kommer jeg tilbage til den når jeg engang er løbet tør for andre ting. :)

**Comment by troldmand** [comment]
Wooooops

**Comment by dotnetCarpenter** [comment]
signup has basic styling. Closing this and will create a new one for the web component part
