### ISSUE TITLE
Left-heading

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#4]
A big heading with a black left justified box. h1

```
BLOCK f-left-heading
```

![left-heading](https://cloud.githubusercontent.com/assets/43763/14753435/b7eda602-08d5-11e6-81e7-530d317244f6.png)

**Comment by troldmand** [comment]
@dotnetCarpenter den her vs. #37 - skal jeg ikke bare lave en modifier der hedder f-left-heading_big?

**Comment by troldmand** [comment]
@dotnetCarpenter evt. også #42, right-side heading?

**Comment by dotnetCarpenter** [comment]
#42 tror jeg skal være sin egen block
