### ISSUE TITLE
f-donate-button

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#40]
```
BLOCK f-donate-button
MODIFIER f-donate-button_attention
```

![f-button](https://cloud.githubusercontent.com/assets/43763/14767921/897a443e-0a32-11e6-8c4c-fffdd0b73d59.png)

**Comment by dotnetCarpenter** [comment]
We MUST change the name

**Comment by troldmand** [comment]
@dotnetCarpenter it's two different button. The top one leads you to the page where you fill out a form when you want to organize a crowdfunding campaign. I'm going to split them up, I think....

**Comment by troldmand** [comment]
@dotnetCarpenter fuck it, I'm gonna make a modifier on the f-button

**Comment by dotnetCarpenter** [comment]
Yeah lets take a look together when we do #67
