### ISSUE TITLE
Button group (3) f-button-group

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#5]
A container that put 3 buttons per row with equal space between them, where the first and last button are justified to the edge.

```
BLOCK f-button-group
    ELEMENT f-button-group__button
    MODIFIER f-button-group__button_active
```

![button-group](https://cloud.githubusercontent.com/assets/43763/14753537/4e2c6464-08d6-11e6-8c78-7636f6ab3672.png)

**Comment by dotnetCarpenter** [comment]
Use [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by troldmand** [comment]
OK!

**Comment by dotnetCarpenter** [comment]
Remember to go through this when we do #67

**Comment by troldmand** [comment]
@magiker420 @dotnetCarpenter feel free to check out the effect and styling. 

I'm not satisfied yet - because it needs a 'click-effect' - something that states too the user, that something does happen when you click a button. It does show that now, from the button they are coming from loosing it's effect, but maybe that's a bit to subtle? 

Oh and it should work on mobile now, but I should implement the cycles instead.

**Comment by dotnetCarpenter** [comment]
@troldmand what branch?

**Comment by dotnetCarpenter** [comment]
#67 button-group
