### ISSUE TITLE
Small text snippets

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#6]
Used on our Manifest page (About Codex-01)

This might be a duplicate 

```
BLOCK f-small-text
    MODIFIER f-small-text_attention
    ELEMENT f-small-text__heading
    ELEMENT f-small-text__text
```

**Comment by troldmand** [comment]
Hm. Maybe it's not a duplicate? I mean, we have lots of similar texts (on IPS,  nr. 14 and nr. 6..) but this one needs to be in two columns - so maybe that's enough to make it it's own block?

**Comment by dotnetCarpenter** [comment]
yes, just add `MODIFIER f-small-text_attention` to #14, rename it to `f-text_attention`, and decide exactly which design we should use.

**Comment by troldmand** [comment]
Cool!
