### ISSUE TITLE
Documentation wizard - f-accordian

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#7]
A container that has some visible text but via a click can display much more text.

```
BLOCK f-accordian
MODIFIER f-accordian_attention
    ELEMENT f-accordian__heading
    ELEMENT f-accordian__cuff-text
    ELEMENT f-accordian__arrow
    MODIFIER f-accordian__arrow_active

```

![accordian](https://cloud.githubusercontent.com/assets/43763/14753678/1f253564-08d7-11e6-9562-10c496eba320.png)

**Comment by dotnetCarpenter** [comment]
This issue was moved to Firefund/frontend#1

**Comment by dotnetCarpenter** [comment]
We'll keep our issues in styleguide while migrating to frontend

**Comment by dotnetCarpenter** [comment]
![skaermbillede 2016-05-28 kl 14 01 23](https://cloud.githubusercontent.com/assets/43763/15627227/8e6c17e0-24dd-11e6-86f3-5b044ccb01f1.png)
New feature!
