### ISSUE TITLE
f-button

### ISSUE THREAD

**Issue by troldmand** [Firefund/styleguide#8]
This is the updated structure of buttons. 
Branch is now called 8-buttom

```
BLOCK f-button
    MODIFIER f-button_encrypt
    MODIFIER f-button_reset
    MODIFIER f-button_submit
    ELEMENT f-button__donate
    MODIFIER f-button__donate_A
    MODIFIER f-button__donate_B
    ELEMENT f-button__organize
    ~MODIFIER f-button__organize_now~
    ELEMENT f-button__share
```

There is also the 5-button-group issue, and 5-button-group branch - but that's special and you can see the relationsship here: 
![skaermbillede 2016-05-05 kl 15 26 08](https://cloud.githubusercontent.com/assets/9819978/15044574/c1a4b3de-12d5-11e6-8b8a-7794eea4b234.png)

**Comment by troldmand** [comment]
I can't find it on the design :o

**Comment by dotnetCarpenter** [comment]
I've updated the issue with an image

**Comment by troldmand** [comment]
I've changed this to be: 

```
BLOCK f-button
    MODIFIER f-button_attention
```

... and more modifiers might be added. :-)

**Comment by dotnetCarpenter** [comment]
Remember to go through this when we do #67

**Comment by dotnetCarpenter** [comment]
Remember to go through this when we do #67

**Comment by troldmand** [comment]
@dotnetCarpenter Check out my update.

**Comment by troldmand** [comment]
Oh, message for myself: Remember to incorporate #10 and #41 !

**Comment by troldmand** [comment]
@dotnetCarpenter we need to talk about this, I'm afraid. I'm stuck and I think you can help me.

**Comment by dotnetCarpenter** [comment]
got it! :) :dancers:

**Comment by dotnetCarpenter** [comment]
changes are merged into master but we need to revisit this when we use the buttons in different blocks-

**Comment by dotnetCarpenter** [comment]
Need to be split into several BEM blocks. @troldmand @dotnetCarpenter

**Comment by dotnetCarpenter** [comment]
@troldmand  Let's keep all the buttons in f-button.css even if they are several BEM blocks

**Comment by dotnetCarpenter** [comment]
@troldmand scratch that. I'll do the buttons as we need them. I'll do the most basic and then we can go through the design later. When you come back I think we'll make quick review with the design doc at our side. Then when the Web components are more done, we can look at fine tuning the animations. We got 3 days left! Yeah, getting a bit stressed
